clear
echo Removing previous pyBioLab folder...
rm -rf build
echo Removing old library in Examples folder...
rm -rf examples/pybiolab
echo Building pyBiolab...
python setup.py build
echo Moving pyBioLab...
mv -f build/lib/pybiolab examples/pybiolab
echo Fixing permissions
chown -Rv username examples/pybiolab